// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: proto/product/v1/product_service.proto

package productpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category             string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	BasePriceNumerator   int64                  `protobuf:"varint,4,opt,name=base_price_numerator,json=basePriceNumerator,proto3" json:"base_price_numerator,omitempty"`
	BasePriceDenominator int64                  `protobuf:"varint,5,opt,name=base_price_denominator,json=basePriceDenominator,proto3" json:"base_price_denominator,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetBasePriceNumerator() int64 {
	if x != nil {
		return x.BasePriceNumerator
	}
	return 0
}

func (x *CreateProductRequest) GetBasePriceDenominator() int64 {
	if x != nil {
		return x.BasePriceDenominator
	}
	return 0
}

type CreateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReply) Reset() {
	*x = CreateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReply) ProtoMessage() {}

func (x *CreateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReply.ProtoReflect.Descriptor instead.
func (*CreateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductReply) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UpdateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReply) Reset() {
	*x = UpdateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReply) ProtoMessage() {}

func (x *UpdateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReply.ProtoReflect.Descriptor instead.
func (*UpdateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{3}
}

type ActivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProductRequest) Reset() {
	*x = ActivateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProductRequest) ProtoMessage() {}

func (x *ActivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProductRequest.ProtoReflect.Descriptor instead.
func (*ActivateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{4}
}

func (x *ActivateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ActivateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProductReply) Reset() {
	*x = ActivateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProductReply) ProtoMessage() {}

func (x *ActivateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProductReply.ProtoReflect.Descriptor instead.
func (*ActivateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{5}
}

type DeactivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductRequest) Reset() {
	*x = DeactivateProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductRequest) ProtoMessage() {}

func (x *DeactivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductRequest.ProtoReflect.Descriptor instead.
func (*DeactivateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeactivateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type DeactivateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductReply) Reset() {
	*x = DeactivateProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductReply) ProtoMessage() {}

func (x *DeactivateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductReply.ProtoReflect.Descriptor instead.
func (*DeactivateProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{7}
}

type ApplyDiscountRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProductId          string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PercentNumerator   int64                  `protobuf:"varint,2,opt,name=percent_numerator,json=percentNumerator,proto3" json:"percent_numerator,omitempty"`
	PercentDenominator int64                  `protobuf:"varint,3,opt,name=percent_denominator,json=percentDenominator,proto3" json:"percent_denominator,omitempty"`
	StartTimestamp     int64                  `protobuf:"varint,4,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp       int64                  `protobuf:"varint,5,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplyDiscountRequest) Reset() {
	*x = ApplyDiscountRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDiscountRequest) ProtoMessage() {}

func (x *ApplyDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDiscountRequest.ProtoReflect.Descriptor instead.
func (*ApplyDiscountRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyDiscountRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ApplyDiscountRequest) GetPercentNumerator() int64 {
	if x != nil {
		return x.PercentNumerator
	}
	return 0
}

func (x *ApplyDiscountRequest) GetPercentDenominator() int64 {
	if x != nil {
		return x.PercentDenominator
	}
	return 0
}

func (x *ApplyDiscountRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *ApplyDiscountRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

type ApplyDiscountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDiscountReply) Reset() {
	*x = ApplyDiscountReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDiscountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDiscountReply) ProtoMessage() {}

func (x *ApplyDiscountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDiscountReply.ProtoReflect.Descriptor instead.
func (*ApplyDiscountReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{9}
}

type RemoveDiscountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDiscountRequest) Reset() {
	*x = RemoveDiscountRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDiscountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDiscountRequest) ProtoMessage() {}

func (x *RemoveDiscountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDiscountRequest.ProtoReflect.Descriptor instead.
func (*RemoveDiscountRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveDiscountRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type RemoveDiscountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDiscountReply) Reset() {
	*x = RemoveDiscountReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDiscountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDiscountReply) ProtoMessage() {}

func (x *RemoveDiscountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDiscountReply.ProtoReflect.Descriptor instead.
func (*RemoveDiscountReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{11}
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductReply struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProductId            string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category             string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	BasePriceNumerator   int64                  `protobuf:"varint,5,opt,name=base_price_numerator,json=basePriceNumerator,proto3" json:"base_price_numerator,omitempty"`
	BasePriceDenominator int64                  `protobuf:"varint,6,opt,name=base_price_denominator,json=basePriceDenominator,proto3" json:"base_price_denominator,omitempty"`
	Status               string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Discount             *Discount              `protobuf:"bytes,8,opt,name=discount,proto3,oneof" json:"discount,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetProductReply) Reset() {
	*x = GetProductReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReply) ProtoMessage() {}

func (x *GetProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReply.ProtoReflect.Descriptor instead.
func (*GetProductReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetProductReply) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetProductReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetProductReply) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetProductReply) GetBasePriceNumerator() int64 {
	if x != nil {
		return x.BasePriceNumerator
	}
	return 0
}

func (x *GetProductReply) GetBasePriceDenominator() int64 {
	if x != nil {
		return x.BasePriceDenominator
	}
	return 0
}

func (x *GetProductReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetProductReply) GetDiscount() *Discount {
	if x != nil {
		return x.Discount
	}
	return nil
}

type Discount struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PercentNumerator   int64                  `protobuf:"varint,1,opt,name=percent_numerator,json=percentNumerator,proto3" json:"percent_numerator,omitempty"`
	PercentDenominator int64                  `protobuf:"varint,2,opt,name=percent_denominator,json=percentDenominator,proto3" json:"percent_denominator,omitempty"`
	StartTimestamp     int64                  `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp       int64                  `protobuf:"varint,4,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Discount) Reset() {
	*x = Discount{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discount) ProtoMessage() {}

func (x *Discount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discount.ProtoReflect.Descriptor instead.
func (*Discount) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{14}
}

func (x *Discount) GetPercentNumerator() int64 {
	if x != nil {
		return x.PercentNumerator
	}
	return 0
}

func (x *Discount) GetPercentDenominator() int64 {
	if x != nil {
		return x.PercentDenominator
	}
	return 0
}

func (x *Discount) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *Discount) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductInfo         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListProductsReply) GetProducts() []*ProductInfo {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ProductInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	mi := &file_proto_product_v1_product_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_service_proto_rawDescGZIP(), []int{17}
}

func (x *ProductInfo) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_product_v1_product_service_proto protoreflect.FileDescriptor

const file_proto_product_v1_product_service_proto_rawDesc = "" +
	"\n" +
	"&proto/product/v1/product_service.proto\x12\n" +
	"product.v1\"\xd0\x01\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x120\n" +
	"\x14base_price_numerator\x18\x04 \x01(\x03R\x12basePriceNumerator\x124\n" +
	"\x16base_price_denominator\x18\x05 \x01(\x03R\x14basePriceDenominator\"3\n" +
	"\x12CreateProductReply\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x87\x01\n" +
	"\x14UpdateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\x14\n" +
	"\x12UpdateProductReply\"7\n" +
	"\x16ActivateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x16\n" +
	"\x14ActivateProductReply\"9\n" +
	"\x18DeactivateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x18\n" +
	"\x16DeactivateProductReply\"\xe1\x01\n" +
	"\x14ApplyDiscountRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12+\n" +
	"\x11percent_numerator\x18\x02 \x01(\x03R\x10percentNumerator\x12/\n" +
	"\x13percent_denominator\x18\x03 \x01(\x03R\x12percentDenominator\x12'\n" +
	"\x0fstart_timestamp\x18\x04 \x01(\x03R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x05 \x01(\x03R\fendTimestamp\"\x14\n" +
	"\x12ApplyDiscountReply\"6\n" +
	"\x15RemoveDiscountRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x15\n" +
	"\x13RemoveDiscountReply\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\xc6\x02\n" +
	"\x0fGetProductReply\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x120\n" +
	"\x14base_price_numerator\x18\x05 \x01(\x03R\x12basePriceNumerator\x124\n" +
	"\x16base_price_denominator\x18\x06 \x01(\x03R\x14basePriceDenominator\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x125\n" +
	"\bdiscount\x18\b \x01(\v2\x14.product.v1.DiscountH\x00R\bdiscount\x88\x01\x01B\v\n" +
	"\t_discount\"\xb6\x01\n" +
	"\bDiscount\x12+\n" +
	"\x11percent_numerator\x18\x01 \x01(\x03R\x10percentNumerator\x12/\n" +
	"\x13percent_denominator\x18\x02 \x01(\x03R\x12percentDenominator\x12'\n" +
	"\x0fstart_timestamp\x18\x03 \x01(\x03R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x04 \x01(\x03R\fendTimestamp\"m\n" +
	"\x13ListProductsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"p\n" +
	"\x11ListProductsReply\x123\n" +
	"\bproducts\x18\x01 \x03(\v2\x17.product.v1.ProductInfoR\bproducts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"t\n" +
	"\vProductInfo\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\xb1\x05\n" +
	"\x0eProductService\x12Q\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a\x1e.product.v1.CreateProductReply\x12Q\n" +
	"\rUpdateProduct\x12 .product.v1.UpdateProductRequest\x1a\x1e.product.v1.UpdateProductReply\x12W\n" +
	"\x0fActivateProduct\x12\".product.v1.ActivateProductRequest\x1a .product.v1.ActivateProductReply\x12]\n" +
	"\x11DeactivateProduct\x12$.product.v1.DeactivateProductRequest\x1a\".product.v1.DeactivateProductReply\x12Q\n" +
	"\rApplyDiscount\x12 .product.v1.ApplyDiscountRequest\x1a\x1e.product.v1.ApplyDiscountReply\x12T\n" +
	"\x0eRemoveDiscount\x12!.product.v1.RemoveDiscountRequest\x1a\x1f.product.v1.RemoveDiscountReply\x12H\n" +
	"\n" +
	"GetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x1b.product.v1.GetProductReply\x12N\n" +
	"\fListProducts\x12\x1f.product.v1.ListProductsRequest\x1a\x1d.product.v1.ListProductsReplyB4Z2product-catalog-service/proto/product/v1;productpbb\x06proto3"

var (
	file_proto_product_v1_product_service_proto_rawDescOnce sync.Once
	file_proto_product_v1_product_service_proto_rawDescData []byte
)

func file_proto_product_v1_product_service_proto_rawDescGZIP() []byte {
	file_proto_product_v1_product_service_proto_rawDescOnce.Do(func() {
		file_proto_product_v1_product_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_service_proto_rawDesc), len(file_proto_product_v1_product_service_proto_rawDesc)))
	})
	return file_proto_product_v1_product_service_proto_rawDescData
}

var file_proto_product_v1_product_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_product_v1_product_service_proto_goTypes = []any{
	(*CreateProductRequest)(nil),     // 0: product.v1.CreateProductRequest
	(*CreateProductReply)(nil),       // 1: product.v1.CreateProductReply
	(*UpdateProductRequest)(nil),     // 2: product.v1.UpdateProductRequest
	(*UpdateProductReply)(nil),       // 3: product.v1.UpdateProductReply
	(*ActivateProductRequest)(nil),   // 4: product.v1.ActivateProductRequest
	(*ActivateProductReply)(nil),     // 5: product.v1.ActivateProductReply
	(*DeactivateProductRequest)(nil), // 6: product.v1.DeactivateProductRequest
	(*DeactivateProductReply)(nil),   // 7: product.v1.DeactivateProductReply
	(*ApplyDiscountRequest)(nil),     // 8: product.v1.ApplyDiscountRequest
	(*ApplyDiscountReply)(nil),       // 9: product.v1.ApplyDiscountReply
	(*RemoveDiscountRequest)(nil),    // 10: product.v1.RemoveDiscountRequest
	(*RemoveDiscountReply)(nil),      // 11: product.v1.RemoveDiscountReply
	(*GetProductRequest)(nil),        // 12: product.v1.GetProductRequest
	(*GetProductReply)(nil),          // 13: product.v1.GetProductReply
	(*Discount)(nil),                 // 14: product.v1.Discount
	(*ListProductsRequest)(nil),      // 15: product.v1.ListProductsRequest
	(*ListProductsReply)(nil),        // 16: product.v1.ListProductsReply
	(*ProductInfo)(nil),              // 17: product.v1.ProductInfo
}
var file_proto_product_v1_product_service_proto_depIdxs = []int32{
	14, // 0: product.v1.GetProductReply.discount:type_name -> product.v1.Discount
	17, // 1: product.v1.ListProductsReply.products:type_name -> product.v1.ProductInfo
	0,  // 2: product.v1.ProductService.CreateProduct:input_type -> product.v1.CreateProductRequest
	2,  // 3: product.v1.ProductService.UpdateProduct:input_type -> product.v1.UpdateProductRequest
	4,  // 4: product.v1.ProductService.ActivateProduct:input_type -> product.v1.ActivateProductRequest
	6,  // 5: product.v1.ProductService.DeactivateProduct:input_type -> product.v1.DeactivateProductRequest
	8,  // 6: product.v1.ProductService.ApplyDiscount:input_type -> product.v1.ApplyDiscountRequest
	10, // 7: product.v1.ProductService.RemoveDiscount:input_type -> product.v1.RemoveDiscountRequest
	12, // 8: product.v1.ProductService.GetProduct:input_type -> product.v1.GetProductRequest
	15, // 9: product.v1.ProductService.ListProducts:input_type -> product.v1.ListProductsRequest
	1,  // 10: product.v1.ProductService.CreateProduct:output_type -> product.v1.CreateProductReply
	3,  // 11: product.v1.ProductService.UpdateProduct:output_type -> product.v1.UpdateProductReply
	5,  // 12: product.v1.ProductService.ActivateProduct:output_type -> product.v1.ActivateProductReply
	7,  // 13: product.v1.ProductService.DeactivateProduct:output_type -> product.v1.DeactivateProductReply
	9,  // 14: product.v1.ProductService.ApplyDiscount:output_type -> product.v1.ApplyDiscountReply
	11, // 15: product.v1.ProductService.RemoveDiscount:output_type -> product.v1.RemoveDiscountReply
	13, // 16: product.v1.ProductService.GetProduct:output_type -> product.v1.GetProductReply
	16, // 17: product.v1.ProductService.ListProducts:output_type -> product.v1.ListProductsReply
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_product_v1_product_service_proto_init() }
func file_proto_product_v1_product_service_proto_init() {
	if File_proto_product_v1_product_service_proto != nil {
		return
	}
	file_proto_product_v1_product_service_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_service_proto_rawDesc), len(file_proto_product_v1_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_v1_product_service_proto_goTypes,
		DependencyIndexes: file_proto_product_v1_product_service_proto_depIdxs,
		MessageInfos:      file_proto_product_v1_product_service_proto_msgTypes,
	}.Build()
	File_proto_product_v1_product_service_proto = out.File
	file_proto_product_v1_product_service_proto_goTypes = nil
	file_proto_product_v1_product_service_proto_depIdxs = nil
}
